---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world.fullname" . }}
spec:
  # ... (replicas and selector)
  template:
    # ... (metadata)
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: ACTIVE_PROFILE
              value: {{ .Values.database.activeProfile | quote }}
            - name: DB_HOST_PRIMARY
              value: {{ .Values.database.primaryHost | quote }}
            - name: DB_HOST_SECONDARY
              value: {{ .Values.database.secondaryHost | quote }}
            - name: DB_USER
              value: {{ .Values.database.dbUser | quote }}
            - name: DB_NAME
              value: {{ .Values.database.dbName | quote }}
            # Pulling the password from a Secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.passwordSecretName }}
                  key: password
